SELECT QUANTITY, PRODUCT_NAME
FROM SALES FULL JOIN PRODUCTS
ON SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID;

SELECT *
FROM sales;

SELECT*
FROM PRODUCTS p


SELECT QUANTITY, PRODUCT_NAME
FROM SALES, PRODUCTS;

SELECT SALES.*, PRODUCTS.*
FROM SALES INNER JOIN PRODUCTS ON SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID
WHERE PRODUCT_NAME LIKE '%Phone'; 

SELECT *
FROM SALES
WHERE DATE BETWEEN '2015-11-01' AND '2017-10-01'
ORDER BY DATE DESC;

SELECT SALES.*, PRODUCTS.*
FROM SALES RIGHT JOIN PRODUCTS ON SALES.PRODUCT_ID = PRODUCTS.PRODUCT_ID
WHERE PRODUCT_NAME IN ('Nokia', 'Samsung', 'LG');

SELECT COUNT(*) AS Total_rows, SUM(Quantity) AS Total_products, AVG(Price) AS Avg_price, MIN(Price) AS Min_price, MAX(Price) AS Max_price
FROM SALES;

SELECT AVG(Price) AS AVG_price, COUNT(SALE_ID) AS Total_sells, SUM(Quantity) AS Total_products , AVG(Price) * COUNT(SALE_ID) * SUM(Quantity) AS Brute_Income
FROM SALES
GROUP BY Product_ID;


SELECT COUNT(a.SALE_ID) AS SALES, AVG(PRICE) AS AVG_PRICE, a.PRODUCT_NAME, YEAR_
FROM (SELECT s.SALE_ID, s.PRICE, s.DATE, p.PRODUCT_NAME, YEAR(s.DATE) as YEAR_  
	  FROM SALES s INNER JOIN PRODUCTS p ON s.PRODUCT_ID = p.PRODUCT_ID 
	  WHERE s.DATE >= '2016.10.01' AND s.Quantity >= 10) AS a
GROUP BY a.PRODUCT_NAME, YEAR_;

